version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql  
    ports:
      - '3306:3306'
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/tone:cached   
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    
