version: '3'
services:
  # 本番環境ではRDS
  # db:
    # image: mysql:5.7
    # environment:
      # MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: root
    # ports:
      # - "3306:3306"
    # volumes:
      # - mysql_data:/var/lib/mysql

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/tone # ソースコード変更したらDocker側も即反映されるように
      - public-data:/tone/public
      - tmp-data:/tone/tmp
      - log-data:/tone/log
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    # depends_on:
      # - db # DB側のコンテナが出来上がってからwebを実行する

  nginx:
    build: 
      context: containers/nginx
    ports:
      - "80:80"
    volumes:
      - public-data:/tone/public
      - tmp-data:/tone/tmp
    depends_on:
      - web

volumes:
  # mysql_data:
  public-data:
  tmp-data:
  log-data: