default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: tone_development
  
test:
  <<: *default
  database: tone_test
  
production:
  <<: *default
  database: tone_production
