default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  # dockerの場合はdb,それ以外の場合はlocalhostを指定
  # host: db
  host: localhost

development:
  <<: *default
  database: tone_development
  
test:
  <<: *default
  database: tone_test
  host: test-db
  
production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
 