default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: db

development:
  <<: *default
  database: tone_development
  
test:
  <<: *default
  database: tone_test
  host: test-db
  
production:
  <<: *default
  database: tone_production

  # database: <%= ENV['DB_DATABASE'] %>
  # encoding: utf8mb4
  # charset: utf8mb4
  # collation: utf8mb4_general_ci
  # host: <%= ENV['DB_HOST'] %>
  # username: <%= ENV['DB_USERNAME'] %>
  # password: <%= ENV['DB_PASSWORD'] %>